name: automerge
on:
  - pull_request
  - pull_request_review
  - status
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "underarmour/automerge-action@v0.11.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge,!do not merge 🤯,!Work in progress 🚧"
          MERGE_RETRIES: "2"
